import { Cake, Heart, Users, Gift, Sparkles, Star } from 'lucide-react';

export const PACKAGES = [
  {
    id: 'memory',
    title: 'Memory Forever',
    tagline: 'Preserve the moments that shaped who you are.',
    story:
      "Not every moment needs an occasion. Sometimes the greatest gift is stopping time — and letting everyone who matters share a piece of the story.",
    image: 'https://images.unsplash.com/photo-1639178952543-1c0ea3cbacaa?w=900',
    icon: Sparkles,
    accent: '#9a7a60',
    price: '₹2,999',
    features: [
      'Unlimited multimedia archive',
      'Collaborative story collection',
      'Cinematic memory video',
      'Lifetime access for the whole family',
    ],
    participants: 'Unlimited',
    timeline: 'Lifetime',
    rating: 4.9,
    reviews: 701,
    tag: null,
  },
  {
    id: 'couple',
    title: 'Long Distance Couple',
    tagline: 'Let your love speak for itself — across every mile.',
    story:
      "We help you create intimate moments your partner will feel deeply. From handwritten digital love letters to voice notes from the people who know your story, we craft something that bridges the distance.",
    image: 'https://images.unsplash.com/photo-1540076156429-35ffe82b7870?w=900',
    icon: Heart,
    accent: '#c07a6a',
    price: '₹4,999',
    features: [
      'Intimate love timeline with shared memories',
      'Voice note collection from mutual friends',
      'Photo memories woven into a story',
      'Private gallery only the two of you see',
    ],
    participants: '2 people + contributors',
    timeline: 'Ongoing or one-time',
    rating: 5.0,
    reviews: 612,
    tag: null,
  },
  {
    id: 'birthday',
    title: 'Birthday Experience',
    tagline: 'Celebrate their special day — from anywhere in the world.',
    story:
      'Your team reaches out to their closest friends and family. We collect heartfelt video messages, voice notes, and childhood memories. Then we weave it all into a cinematic surprise delivered on their birthday.',
    image: 'https://images.unsplash.com/photo-1583875762487-5f8f7c718d14?w=900',
    icon: Cake,
    accent: '#d4a574',
    price: '₹6,999',
    features: [
      'Cinematic video montage of collected memories',
      'Heartfelt group messages from loved ones',
      'Surprise coordinated reveal moment',
      'Digital memory timeline, preserved forever',
    ],
    participants: '5–50 people',
    timeline: '7–14 days to prepare',
    rating: 4.9,
    reviews: 847,
    tag: 'Most Loved',
  },
  {
    id: 'wedding',
    title: 'Wedding Surprise',
    tagline: 'Celebrate their beautiful bond and new beginnings — together.',
    story:
      "A wedding is the ultimate union. We help siblings, cousins, childhood friends, and family members compile their blessings, throwback memory photos, and customized video messages, creating a cinematic tribute the couple will cherish forever.",
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=900',
    icon: Heart,
    accent: '#d4a574',
    price: '₹7,999',
    features: [
      'Blessing messages from friends & family worldwide',
      'Childhood memory collage of the bride and groom',
      'Surprise screening video ready for the reception',
      'Elegant digital scrapbook link for guests to view',
    ],
    participants: '10–100 people',
    timeline: '10–20 days',
    rating: 4.9,
    reviews: 482,
    tag: null,
  },
  {
    id: 'parents',
    title: 'Parents Tribute',
    tagline: 'Honor the ones who shaped your world.',
    story:
      "We quietly contact siblings, cousins, childhood friends, and family members to gather the stories only they know. The result is a deeply emotional tribute your parents will watch through tears.",
    image: 'https://images.unsplash.com/photo-1624448445915-97154f5e688c?w=900',
    icon: Users,
    accent: '#c19466',
    price: '₹8,999',
    features: [
      'Family stories collected across generations',
      'Throwback photo contributions from everyone',
      'Grateful video messages from children',
      'A legacy book they keep forever',
    ],
    participants: 'Family members',
    timeline: '2–6 weeks',
    rating: 4.9,
    reviews: 523,
    tag: null,
  },
];
