import { Cake, Heart, Users, Gift, Sparkles } from 'lucide-react';

export const PACKAGES = [
  {
    id: 'birthday',
    title: 'Birthday Experience',
    tagline: 'Celebrate their special day — from anywhere in the world.',
    story:
      'Your team reaches out to their closest friends and family. We collect heartfelt video messages, voice notes, and childhood memories. Then we weave it all into a cinematic surprise delivered on their birthday.',
    image: 'https://images.unsplash.com/photo-1583875762487-5f8f7c718d14?w=900',
    icon: Cake,
    accent: '#d4a574',
    price: '₹14,999',
    features: [
      'Cinematic video montage of collected memories',
      'Heartfelt group messages from loved ones',
      'Surprise coordinated reveal moment',
      'Digital memory timeline, preserved forever',
    ],
    participants: '5–50 people',
    timeline: '7–14 days to prepare',
    rating: 4.9,
    reviews: 847,
    tag: 'Most Loved',
  },
  {
    id: 'couple',
    title: 'Long Distance Couple',
    tagline: 'Let your love speak for itself — across every mile.',
    story:
      "We help you create intimate moments your partner will feel deeply. From handwritten digital love letters to voice notes from the people who know your story, we craft something that bridges the distance.",
    image: 'https://images.unsplash.com/photo-1540076156429-35ffe82b7870?w=900',
    icon: Heart,
    accent: '#c07a6a',
    price: '₹9,999',
    features: [
      'Intimate love timeline with shared memories',
      'Voice note collection from mutual friends',
      'Photo memories woven into a story',
      'Private gallery only the two of you see',
    ],
    participants: '2 people + contributors',
    timeline: 'Ongoing or one-time',
    rating: 5.0,
    reviews: 612,
    tag: null,
  },
  {
    id: 'parents',
    title: 'Parents Tribute',
    tagline: 'Honor the ones who shaped your world.',
    story:
      "We quietly contact siblings, cousins, childhood friends, and family members to gather the stories only they know. The result is a deeply emotional tribute your parents will watch through tears.",
    image: 'https://images.unsplash.com/photo-1624448445915-97154f5e688c?w=900',
    icon: Users,
    accent: '#c19466',
    price: '₹18,999',
    features: [
      'Family stories collected across generations',
      'Throwback photo contributions from everyone',
      'Grateful video messages from children',
      'A legacy book they keep forever',
    ],
    participants: 'Family members',
    timeline: '2–6 weeks',
    rating: 4.9,
    reviews: 523,
    tag: null,
  },
  {
    id: 'appreciation',
    title: 'Appreciation Surprise',
    tagline: 'Show someone they matter — more than words alone.',
    story:
      "Sometimes the most meaningful thing is telling someone what they've done for you. We help you gather stories of impact from everyone their life has touched.",
    image: 'https://images.unsplash.com/photo-1674570980050-b5b06b08d7ad?w=900',
    icon: Gift,
    accent: '#b8855a',
    price: '₹11,999',
    features: [
      'Impact stories from people they helped',
      'Gratitude messages crafted with care',
      'Photo collage of shared moments',
      'A surprise celebration moment',
    ],
    participants: '3–30 people',
    timeline: '5–10 days',
    rating: 4.8,
    reviews: 391,
    tag: null,
  },
  {
    id: 'memory',
    title: 'Memory Forever',
    tagline: 'Preserve the moments that shaped who you are.',
    story:
      "Not every moment needs an occasion. Sometimes the greatest gift is stopping time — and letting everyone who matters share a piece of the story.",
    image: 'https://images.unsplash.com/photo-1639178952543-1c0ea3cbacaa?w=900',
    icon: Sparkles,
    accent: '#9a7a60',
    price: '₹4,999',
    features: [
      'Unlimited multimedia archive',
      'Collaborative story collection',
      'Cinematic memory video',
      'Lifetime access for the whole family',
    ],
    participants: 'Unlimited',
    timeline: 'Lifetime',
    rating: 4.9,
    reviews: 701,
    tag: null,
  },
];
